name: deploy
on: [push, pull_request]
# on:
#   push:
#     branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
        S_NAME: ${{ secrets.SERVER_NAME }}
        S_PASSWORD: ${{ secrets.YANDEX_SSH }}
    steps:
    - uses: actions/checkout@v3
    
    - uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.YANDEX_SSH }}
        known_hosts: ${{ secrets.YANDEX_HOST }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.8

    - name: Build
      run: go build -o botapp cmd/main.go

    - name: Deploy
      run: |
        pwd
        ls
        rsync -avze "ssh -o StrictHostKeyChecking=no -i sshkey" ./* "$S_NAME":/gobot/
        
