name: runLinters
on: [push, pull_request]

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          github-token: ${{ github.token }}
          only-new-issues: true
